version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "16:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.1
    - 12.1.0
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.1
    - 12.1.0
  - dependency-name: "@semantic-release/npm"
    versions:
    - 7.0.10
    - 7.1.0
  - dependency-name: "@semantic-release/github"
    versions:
    - 7.2.0
  - dependency-name: "@semantic-release/release-notes-generator"
    versions:
    - 9.0.1
  commit-message:
    prefix: chore
    include: scope
  registries:
  - npm-registry-registry-npmjs-org
